### ISSUE TITLE
Send Requests async

### ISSUE THREAD

**Issue by GrzesiekP** [smartystreets/smartystreets-dotnet-sdk#10]
Have you been thinking about adding SendAsync method ti IClient? 
I've made a quick research and the biggest this is, that it would require cutting off .NET 3.5 as it does not support Task<T>.

**Comment by mdwhatcott** [comment]
See previous discussion: https://github.com/smartystreets/smartystreets-dotnet-sdk/pull/1#issuecomment-257563204

**Comment by ryanjerskine** [comment]
Any chance this could be revisited? I have a PR ready to go adding Async and dropping 3.5 and 4.0 since they aren't supported anymore.

**Comment by joliver** [comment]
Typically what we have seen is for those that need direct async support, they simply wrap the synchronous call in a Task<T> and then use the async capabilities of the Task Parallel Library.

**Comment by ryanjerskine** [comment]
> Typically what we have seen is for those that need direct async support, they simply wrap the synchronous call in a Task and then use the async capabilities of the Task Parallel Library.

That doesn't help me with anything. Using Task.Run will just pull another thread from the thread pool and block on that thread (slowing things down even more with the overhead of doing that). I'm wanting async for scalability, not to avoid blocking on a UI thread.

**Comment by jumpingjackson** [comment]
Yeah i think its pretty silly there is no async api

**Comment by Fullmight** [comment]
Like, "they simply wrap the synchronous call in a Task"? Git isuses are a weird place for a standup routine, and since we all know that doesn't work it has to be a joke right?

**Comment by ConnorCallison** [comment]
An API client that only offers unnecessarily blocking calls on network IO does not deserve to be used in production. This is a bare minimum capability I would expect of the smarty SDK.

Its not confidence inspiring that this has been an issue since 2016.
