### ISSUE TITLE
OpenAPI Specification

### ISSUE THREAD

**Issue by ryanjerskine** [smartystreets/smartystreets-dotnet-sdk#13]
It looks like you guys are maintaining 8 different SDKs. Wouldn't it be easier to just provide us with something like an OpenAPI spec so that we could generate clients in any language? Would you be open to a PR somewhere that added a basic OpenAPI spec yaml/json file?

**Comment by joliver** [comment]
You're in luck:

https://github.com/smartystreets/openapi-specification
