### ISSUE TITLE
Supported SSL / security protocol options?

### ISSUE THREAD

**Issue by shuhkla** [smartystreets/smartystreets-dotnet-sdk#14]
Currently, we're getting an SSL related exception when we attempt to invoke Send method with ClientBuilder:

> System.Net.WebException: The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream. ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.Security.SslState.ThrowIfExceptional()
>    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
>    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
>    at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at System.Net.HttpWebRequest.SendRequest()
>    at System.Net.HttpWebRequest.GetResponse()
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at SmartyStreets.NativeSender.GetResponse(WebRequest request)
>    at SmartyStreets.NativeSender.Send(Request request)
>    at SmartyStreets.StatusCodeSender.Send(Request request)
>    at SmartyStreets.RetrySender.TrySend(Request request, Int32 attempt)
>    at SmartyStreets.RetrySender.Send(Request request)
>    at SmartyStreets.USStreetApi.Client.Send(Batch batch)
>    at LPS.Services.SmartyStreetsService.Verify(Address address) in C:\Jenkins\workspace\LPS_IIS_SOM_DEV (R2 Sprint)\src\LPS.Services\SmartyStreetsService.cs:line 60
>    at LPS.WebApplication.Controllers.SmartyStreetsController.Post(Address model) in C:\Jenkins\workspace\LPS_IIS_SOM_DEV (R2 Sprint)\src\LPS.WebApplication\Controllers\SmartyStreetsController.cs:line 28
>    at lambda_method(Closure , Object , Object[] )
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
>    at LPS.WebApplication.Middleware.ApiKeyMiddleware.Invoke(HttpContext context) in C:\Jenkins\workspace\LPS_IIS_SOM_DEV (R2 Sprint)\src\LPS.WebApplication\Middleware\ApiKeyMiddleware.cs:line 34
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
>    at LPS.WebApplication.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext httpContext, ILogger`1 logger, IHostingEnvironment environment) in C:\Jenkins\workspace\LPS_IIS_SOM_DEV (R2 Sprint)\src\LPS.WebApplication\GlobalExceptionHandlerMiddleware.cs:line 28

This seems to be a security protocol related issue that SmartyStreets endpoint is rejecting our request for. What are the supported SSL options?

**Comment by joliver** [comment]
What version of Windows is this running on?

**Comment by shuhkla** [comment]
Windows Server 2016

**Comment by joliver** [comment]
I'm wondering if this is a .NET Core issue:

https://github.com/dotnet/core/issues/1696#issuecomment-399701130

The above thread talks about setting the `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=false` environment variable even on Windows Server 2016 and it solved it.

**Comment by shuhkla** [comment]
Just tried it out, now I'm getting a different error:

> System.Net.WebException: An error occurred while sending the request. Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 
> 'A connection with the server could not be established'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
> System.Net.Http.WinHttpException: Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.\r\n   
> at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()\r\n   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)\r\n   
> --- End of inner exception stack trace ---\r\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\r\n   
> at System.Net.HttpWebRequest.SendRequest()\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   
> at SmartyStreets.NativeSender.GetResponse(WebRequest request)\r\n   at SmartyStreets.NativeSender.Send(Request request)\r\n   at SmartyStreets.StatusCodeSender.Send(Request request)\r\n   
> at SmartyStreets.RetrySender.TrySend(Request request, Int32 attempt)\r\n   at SmartyStreets.RetrySender.Send(Request request)\r\n   at SmartyStreets.USStreetApi.Client.Send(Batch batch)\r\n   
> at LPS.Services.SmartyStreetsService.Verify(Address address) in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.Services\\SmartyStreetsService.cs:line 60\r\n   
> at LPS.WebApplication.Controllers.SmartyStreetsController.Post(Address model) in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.WebApplication\\Controllers\\SmartyStreetsController.cs:line 28\r\n   
> at lambda_method(Closure , Object , Object[] )\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   
> at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   
> at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)\r\n   
> at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)\r\n   
> at LPS.WebApplication.Middleware.ApiKeyMiddleware.Invoke(HttpContext context) in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.WebApplication\\Middleware\\ApiKeyMiddleware.cs:line 34\r\n   
> at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n  
>  at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\r\n   
>  at LPS.WebApplication.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext httpContext, ILogger`1 logger, IHostingEnvironment environment)
>  in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.WebApplication\\GlobalExceptionHandlerMiddleware.cs:line 28"}

I'm on .System.Net.WebException: An error occurred while sending the request. Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 
'A connection with the server could not be established'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
System.Net.Http.WinHttpException: Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.\r\n   
at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()\r\n   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)\r\n   
--- End of inner exception stack trace ---\r\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\r\n   
at System.Net.HttpWebRequest.SendRequest()\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   
at SmartyStreets.NativeSender.GetResponse(WebRequest request)\r\n   at SmartyStreets.NativeSender.Send(Request request)\r\n   at SmartyStreets.StatusCodeSender.Send(Request request)\r\n   
at SmartyStreets.RetrySender.TrySend(Request request, Int32 attempt)\r\n   at SmartyStreets.RetrySender.Send(Request request)\r\n   at SmartyStreets.USStreetApi.Client.Send(Batch batch)\r\n   
at LPS.Services.SmartyStreetsService.Verify(Address address) in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.Services\\SmartyStreetsService.cs:line 60\r\n   
at LPS.WebApplication.Controllers.SmartyStreetsController.Post(Address model) in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.WebApplication\\Controllers\\SmartyStreetsController.cs:line 28\r\n   
at lambda_method(Closure , Object , Object[] )\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   
at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)\r\n   
at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)\r\n   
at LPS.WebApplication.Middleware.ApiKeyMiddleware.Invoke(HttpContext context) in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.WebApplication\\Middleware\\ApiKeyMiddleware.cs:line 34\r\n   
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n  
 at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\r\n   
 at LPS.WebApplication.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext httpContext, ILogger`1 logger, IHostingEnvironment environment)
 in C:\\Jenkins\\workspace\\LPS_IIS_SOM_DEV (R2 Sprint)\\src\\LPS.WebApplication\\GlobalExceptionHandlerMiddleware.cs:line 28"
