### ISSUE TITLE
Autocomplete geolocate when going through a proxy

### ISSUE THREAD

**Issue by nehme-bilal-ah** [smartystreets/smartystreets-dotnet-sdk#16]
The documentation of the autocomplete API suggests that it's possible to geolocate when going through a proxy:
```
Whether to prefer address suggestions in the user's city and state, based on their IP address. (If the request to the Autocomplete API goes through a proxy, you will need to set an X-Forwarded-For header specifying the user's IP address.)
```
Is this supported by the C# SDK?

**Comment by MouaYing** [comment]
The .NET (C#) SDK unfortunately does not yet support adding custom headers, which would be required to make this work. We may provide this in the future.

**Comment by nehme-bilal-ah** [comment]
That would be great.

**Comment by DuncanBeutler** [comment]
@nehme-bilal-ah custom headers are now supported by this SDK. Let us know if you have any issues with this in the future!
