### ISSUE TITLE
TLS 1.2 Compliance

### ISSUE THREAD

**Issue by uts-pw** [smartystreets/smartystreets-dotnet-sdk#17]
If we are using this library to execute API calls currently does the most recent version (8.3 as of this post) cover the TLS issues mentioned in this blog post? Or are there additional changes we need to make in our app

[SmartStreets blog post](https://smartystreets.com/blog/2019/10/removing-old-versions-of-tls)

**Comment by joliver** [comment]
The SDK itself doesn't dictate what version of TLS to use. That's an application-wide setting that can be set during startup: https://stackoverflow.com/a/26392698/151741

```
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```
