### ISSUE TITLE
USAutoComplete Pro isn't available

### ISSUE THREAD

**Issue by ShagunParikh** [smartystreets/smartystreets-dotnet-sdk#19]
There are 2 versions of US Auto Complete API as per https://smartystreets.com/docs/cloud/us-autocomplete-api

But I couldn't find a way to access **Pro** US Autocomplete API via .Net SDK.

Strange that is available in Java SDK but not in .Net SDK? I really need it in .Net though - specially zip code in suggestions.

Any possible way?

**Comment by mdwhatcott** [comment]
The US Autocomplete Pro API is only available in the Java and Javascript SDKs. The US Autocomplete Pro API only accepts [website key authentication](https://smartystreets.com/docs/cloud/authentication#htmlkeys), which effectively limits which languages it makes sense to implement a client in.

**Comment by ShagunParikh** [comment]
I see. Thanks for the info.
