### ISSUE TITLE
Registering smarty streets with DI - Missing IInternationalStreetClient in 8.4.1 library?

### ISSUE THREAD

**Issue by xantari** [smartystreets/smartystreets-dotnet-sdk#20]
I need to register two different clients in both my units tests (need to mock the client) and in my application. One for international addresses and one for US Street addresses)

It appears your source contains IInternationalStreetClient and IUSStreetClient

But when using the 8.4.1 SDK I can't seem to find these anywhere in the library.

How to use with DI without these two interfaces (IInternationalStreetClient  and IUSStreetClient)?

**Comment by mdwhatcott** [comment]
Yes, those marker interfaces were merged as part of PR #18 but hadn't been published in a tagged release. I just published version `8.5.0` to nuget.

- https://www.nuget.org/packages/smartystreets-dotnet-sdk/
- https://github.com/smartystreets/smartystreets-dotnet-sdk/releases/tag/8.5.0

**Comment by xantari** [comment]
Thank you!
