### ISSUE TITLE
Autocomplete PRO

### ISSUE THREAD

**Issue by Mister8bal** [smartystreets/smartystreets-dotnet-sdk#24]
How can I access the pro version of autocomplete?

**Comment by mdwhatcott** [comment]
@Mister8bal - The [US Autocomplete Pro API](https://smartystreets.com/docs/cloud/us-autocomplete-pro-api) is only accessible from client-side environments like a web browser or mobile app. For this reason the only SDKs to implement a client for the US Autocomplete Pro API are [Javascript](https://github.com/smartystreets/smartystreets-javascript-sdk/), [Java](https://github.com/smartystreets/smartystreets-java-sdk) and [iOS](https://github.com/smartystreets/smartystreets-ios-sdk/).

**Comment by rolando-overactive** [comment]
Hi @mdwhatcott;
automcomplete is still only available for client-side env?

**Comment by DuncanBeutler** [comment]
@rolando-overactive The US Autocomplete Pro API is available on the .NET SDK. The most up-to-date version being 8.10.2
