### ISSUE TITLE
Missing columns 

### ISSUE THREAD

**Issue by rolando-overactive** [smartystreets/smartystreets-dotnet-sdk#27]
Hi,
I would like use the sdk in order to fill the next properties:

```
public class PropertyResult
    {

        public string City { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string PostalCode { get; set; }
    }
```

I've done a small example with the sdk but I found that some properties doesn't exist in the SDK

```
public static PropertyResult ToPropertyResult(this Candidate candidate)
        {
            return new PropertyResult()
            {
                City= string.Empty, // should exist something candidate.components.default_city_name
                Latitude = candidate.Metadata.Latitude.ToString(),
                Longitude = candidate.Metadata.Longitude.ToString(),
                StateCode = string.Empty, //candidate.Components.state_abbreviation
                StateName = string.Empty, //candidate.Components.state_name
                PostalCode = string.Empty // I think we must to call a second api 
            };
        }
```
then only propeties that I can get correctly are Latitude and Longitude but not the others.. any advice?

**Comment by DuncanBeutler** [comment]
The `City` `State` and `PostalCode` fields are all returned on the Components object. PostalCode is named `ZipCode` and the state is returned as the abbreviated form (ex: California -> CA)

So:
City = candidate.Components.CityName
StateName = candidate.Components.State
PostalCode = candidate.Components.ZipCode

**Comment by rolando-overactive** [comment]
ooops my bad. I was using the `SmartyStreets.InternationalStreetApi` namespace.
