### ISSUE TITLE
Smartystreets - Smarty Streets SDK returns null when the direct call to API return value

### ISSUE THREAD

**Issue by rolando-overactive** [smartystreets/smartystreets-dotnet-sdk#28]
Hi team!
we are having an issue using .Net SDK.. Basically:
1. Open https://www.smartystreets.com/products/single-address
2. Open Network tab in Chrome DevTools
3. Input and submit the next address 948 Gorham St Mount Dora FL 32777 (invalid ZIP)
4. We get a response where the zip was corrected.

if you use the same address with the SDK this return null.
**Actual result:**
Smarty Streets SDK returns null when the direct call to API return value

**Expected result:**
Smarty Streets SDK returns the same value as a direct call to API does

Any advice?

**Comment by DuncanBeutler** [comment]
Without seeing your code, it's difficult to diagnose the issue you're experiencing. The first solution that comes to mind without seeing your code is setting the `lookup.MatchStrategy` to `Lookup.ENHANCED`.
If this doesn't work maybe you could provide a snippet of code for me to take a look at.
