### ISSUE TITLE
Latitude/Longitude 

### ISSUE THREAD

**Issue by rolando-overactive** [smartystreets/smartystreets-dotnet-sdk#30]
Hi Team,
I am getting different results related with fields Latitude/Longitude   from the API here: https://www.smartystreets.com/products/apis/us-street-api and the sdk.

Basically I am asking for this address:
```
 var streetAddress = new StreetDto()
            {
                City = "RIVIERA BEACH",
                State = "FL",
                Street = "1221 BIMINI LN",
                Street2 = null,
                ZipCode = "33404",
                MatchStrategy = Lookup.ENHANCED
            };
```
Where the API respond with:  latitude: 26.792206 / longitude: -80.037132

But using the sdk I got this: latitude: 26.792180, longitude: -80.036310.

I am attaching the next image for some extra material:

![image](https://user-images.githubusercontent.com/84352600/133656073-1f6c3529-bafd-4f16-b85d-21b55c562c6d.png)

and a unit test with name `SearchPlacesAsync_ReturnLatitudAndLongitute_Fail`   (check this file: https://github.com/rolando-overactive/smartystreets/blob/main/SmartyStreetsTests/SmartyStreetsServiceTests.cs)

cc: @joliver

**Comment by joliver** [comment]
This looks like a licensing question. Depending upon the license you submit (`us-core-cloud` vs `us-rooftop-geocoding`) the latitude and longitude can differ. The `us-rooftop-geocoding` has the best possible geocoding.

**Comment by rolando-overactive** [comment]
thanks for quick feedback!
