### ISSUE TITLE
Not fully compatible with .NETCoreApp v2.0

### ISSUE THREAD

**Issue by raday** [smartystreets/smartystreets-dotnet-sdk#8]
I'm running a project in .NET CORE 2.0, and I'm constantly getting an error when I build: 
smartystreets-dotnet-sdk 7.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. 
Apparently you're working on compatibility with 2.0.  Your package seems to work fine so far, but you never know.

**Comment by joliver** [comment]
@raday Over the last 4 days we've updated our build process to target .NET 4.0 and .NET Standard 2.0. This is reflected in the [latest build v8.0.3](https://www.nuget.org/packages/smartystreets-dotnet-sdk/8.0.3)

Please point your NuGet references to the latest version and everything should work great with your v4.6.1 project.
