### ISSUE TITLE
InternationalStreetApi.Lookup does not implement ILookup

### ISSUE THREAD

**Issue by blockosmith** [smartystreets/smartystreets-dotnet-sdk#9]
The InternationalStreetApi.LookUp class does not implement the ILookUp interface - is this intentional? I found this issue in a method that returns an ILookUp object. This method can't return an InternationalStreetApi.Lookup without explicitly casting the LookUp first.

**Comment by mdwhatcott** [comment]
This is not intentional--it already has the `InputId` getter. Most of our programming is in more dynamic languages where interfaces are satisfied implicitly (go, python, etc...). Easy fix--stay tuned.

**Comment by MouaYing** [comment]
This has now been fixed. The change is present in version 8.0.11.
